using PRJ.Application.DTOs.Common;

namespace PRJ.Application.DTOs
{
    public class DTOActionCenter : BasedDtoEntity
    {
        public DTOActionCenter()
        {
            this.ItemSourceStatusHistories = new List<DTOItemSourceStatusHistory>();
            this.ItemSourceMsgHistories = new List<DTOItemSourceMsgHistory>();
        }
        public string SourceId { get; set; }
        public string NrrcId { get; set; }// Generated By The System
        public string TransactionTypeEn { get; set; }
        public string TransactionTypeAr { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string EntityEn { get; set; }
        public string EntityAr { get; set; }
        public string FacilityAr { get; set; }
        public string FacilityEn { get; set; }
        public string LicenseEn { get; set; }
        public string LicenseAr { get; set; }
        public string PermitNumber { get; set; }
        public string SourceCode { get; set; }
        public string TransactionStatusEn { get; set; }
        public string TransactionStatusAr { get; set; }
        public int TransactionId { get; set; }
        public string TransactionType { get; set; }

        public int sourceType { get; set; }
        public string SourceTypeEn { get; set; }
        public string SourceTypeAr { get; set; }

        public string CreateUser { get; set; }
        public string ModifiedUser { get; set; }
        public string ConfirmedUser { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public DateTime? ConfirmedDate { get; set; }

        public string ManufacturerEn { get; set; }
        public string ManufacturerAr { get; set; }
        public string ManufacturerSerialNo { get; set; }
        public string ManufacturerCountryEn { get; set; }
        public string ManufacturerCountryAr { get; set; }
        public DateTime? ProductionDate { get; set; }
        public string FacilitySourceID { get; set; }

        public double currentActivity { get; set; }
        public string RadionuclideName { get; set; }

        public string currentSourceStatusAr { get; set; }
        public string currentSourceStatusEn { get; set; }

        public string AssociatedEquipmentAr { get; set; }
        public string AssociatedEquipmentEn { get; set; }
        public string shieldCode { get; set; }
        public int? Quantity { get; set; }
        public List<DTOItemSourceMsgHistory> ItemSourceMsgHistories { get; set; }
        public List<DTOItemSourceStatusHistory> ItemSourceStatusHistories { get; set; }

        public virtual ICollection<DTOGetTransactionAttachments> TransactionAttactcments { get; set; }
        public virtual ICollection<DTOGetTransactionAttachments> ShieldAttachments { get; set; }



    }
}
