//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityRequest()
        {
            this.AgencyLicensors = new HashSet<AgencyLicensor>();
            this.AgencyRelateds = new HashSet<AgencyRelated>();
            this.AgencySupervisors = new HashSet<AgencySupervisor>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public Nullable<int> ActivityKey { get; set; }
        public string ActivityCode { get; set; }
        public string ActivityDescriptionAr { get; set; }
        public string ActivityDescriptionEn { get; set; }
        public string ActivityExplainAr { get; set; }
        public string ActivityExplainEn { get; set; }
        public string ActivityCategory { get; set; }
        public Nullable<bool> IsLicenseNeeded { get; set; }
        public string CoordinatorName { get; set; }
        public string CoordinatorMobile { get; set; }
        public string CoordinatorEmail { get; set; }
        public string SenderName { get; set; }
        public string SenderIdentifier { get; set; }
        public int Status { get; set; }
        public int EditType { get; set; }
        public string SuggestedEditEn { get; set; }
        public string SuggestedEditAr { get; set; }
        public string ExplainEditReason { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyLicensor> AgencyLicensors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencyRelated> AgencyRelateds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgencySupervisor> AgencySupervisors { get; set; }
    }
}
