//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllRequest
    {
        public long Id { get; set; }
        public string UserEmail { get; set; }
        public string Year { get; set; }
        public string Weeks { get; set; }
        public string SuggestedDate { get; set; }
        public Nullable<long> Code { get; set; }
        public string RejectReasonAR { get; set; }
        public string CreatedBy { get; set; }
        public string Semester { get; set; }
        public string Status { get; set; }
        public string EndDate { get; set; }
        public string Created { get; set; }
    }
}
