//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignLink
    {
        public long Id { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string LinkTitle { get; set; }
        public string Link { get; set; }
        public Nullable<long> LinkVisits { get; set; }
    
        public virtual Campaing Campaing { get; set; }
    }
}
