//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaing()
        {
            this.CampaignAttachments = new HashSet<CampaignAttachment>();
            this.CampaignLinks = new HashSet<CampaignLink>();
            this.CustomCompaignMails = new HashSet<CustomCompaignMail>();
        }
    
        public long Id { get; set; }
        public Nullable<int> CampingExternalId { get; set; }
        public string ArTtitle { get; set; }
        public string EnTtitle { get; set; }
        public Nullable<System.DateTime> CampaignTime { get; set; }
        public long SentBy { get; set; }
        public Nullable<bool> HasExceptions { get; set; }
        public Nullable<byte> ExceptionType { get; set; }
        public byte EmailListTypeId { get; set; }
        public Nullable<byte> ContentTypeId { get; set; }
        public Nullable<bool> HasMultiContent { get; set; }
        public Nullable<bool> HasMultiLinks { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
        public Nullable<bool> IsTemplateNeeded { get; set; }
        public Nullable<bool> AttachmentSent { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignAttachment> CampaignAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignLink> CampaignLinks { get; set; }
        public virtual EmailList EmailList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomCompaignMail> CustomCompaignMails { get; set; }
    }
}
