//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaintinanceRequestTask
    {
        public long Id { get; set; }
        public Nullable<long> FkCarMaintinanceRequestId { get; set; }
        public Nullable<long> AssignedTo { get; set; }
        public Nullable<long> FkStatusId { get; set; }
        public string RejectReason { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> Specialist_Payments { get; set; }
        public Nullable<int> Specialist_CarSpeedometer { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> FKRoleId { get; set; }
    }
}
