//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaintinanceRequest
    {
        public long Id { get; set; }
        public Nullable<long> FkEmpId { get; set; }
        public Nullable<long> FkDirectorEmpId { get; set; }
        public Nullable<long> FkCityId { get; set; }
        public Nullable<long> FkCarId { get; set; }
        public Nullable<long> FkCarMainitnanceTypeId { get; set; }
        public Nullable<long> FKSpecialistId { get; set; }
        public Nullable<long> CurrentTaskId { get; set; }
        public string MainitnanceDescription { get; set; }
        public Nullable<bool> IsMaintainanceDone { get; set; }
        public Nullable<decimal> MaintainanceValue { get; set; }
        public string Notes { get; set; }
        public Nullable<int> CarSpeedometer { get; set; }
        public Nullable<decimal> Specialist_Payments { get; set; }
        public Nullable<long> FkStatusId { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SecialistCarSpeedometer { get; set; }
    }
}
