//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarMaintinanceBillsAttachment
    {
        public long Id { get; set; }
        public byte[] AttachmentFile { get; set; }
        public string AttachmentPath { get; set; }
        public string AttachmentName { get; set; }
        public string AttachmentContentType { get; set; }
        public Nullable<bool> IsMaintanianceCard { get; set; }
        public Nullable<long> FkRequestId { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
