//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarRequest
    {
        public long Id { get; set; }
        public Nullable<long> FkEmpId { get; set; }
        public long FkDirectorEmpId { get; set; }
        public Nullable<long> FKSpecialistId { get; set; }
        public long FkCityId { get; set; }
        public int MissionDays { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> EmpLicenseExpiryDate { get; set; }
        public byte[] EmpIDFile { get; set; }
        public string EmpIDFileName { get; set; }
        public string EmpIDFileServerName { get; set; }
        public byte[] EmpDrivingLicenseFile { get; set; }
        public string EmpDrivingLicenseFileName { get; set; }
        public string EmpDrivingLicenseFileServerName { get; set; }
        public byte[] MissionApprovalFile { get; set; }
        public string MissionApprovalFileName { get; set; }
        public string MissionApprovalFileServerName { get; set; }
        public string EmpNotes { get; set; }
        public long FkStatusId { get; set; }
        public Nullable<long> FkCarId { get; set; }
        public byte[] ReceivedCarFile { get; set; }
        public string ReceivedCarFileName { get; set; }
        public string ReceivedCarFileServerName { get; set; }
        public string SpecialistNotes { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
