//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomCompaignMail
    {
        public long Id { get; set; }
        public Nullable<long> CampaignId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<bool> IsLinkVisited { get; set; }
    
        public virtual Campaing Campaing { get; set; }
    }
}
