//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailListContent
    {
        public long Id { get; set; }
        public byte EmailListTypeId { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
    
        public virtual EmailList EmailList { get; set; }
    }
}
