//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpIdentyCertificate
    {
        public long Id { get; set; }
        public Nullable<System.Guid> UId { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public Nullable<int> Gender { get; set; }
        public string EmpName { get; set; }
        public string EmpId { get; set; }
        public string JobTitleCode { get; set; }
        public string JobTitleDescription { get; set; }
        public string JoinDate { get; set; }
        public string WorkLocation { get; set; }
        public Nullable<int> GradeCode { get; set; }
        public string GradeDescription { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> AccomodationAmount { get; set; }
        public Nullable<decimal> TransportationAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string TotalAmountDescription { get; set; }
        public string PrintDate { get; set; }
        public string ExpirePrintDate { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string Lang { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
