//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEvaluation
    {
        public int Id { get; set; }
        public Nullable<long> OracelSerial { get; set; }
        public long EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public long FirstPlanId { get; set; }
        public string FirstPlanNumber { get; set; }
        public long FirstManagementId { get; set; }
        public string FirstManagementName { get; set; }
        public Nullable<decimal> FirstEvaluation { get; set; }
        public Nullable<long> SecondPlanId { get; set; }
        public string SecondPlanNumber { get; set; }
        public Nullable<long> SecondManagementId { get; set; }
        public string SecondManagementName { get; set; }
        public Nullable<decimal> SecondEvaluation { get; set; }
        public Nullable<long> ThirdPlanId { get; set; }
        public string ThirdPlanNumber { get; set; }
        public Nullable<long> ThirdManagementId { get; set; }
        public string ThirdManagementName { get; set; }
        public Nullable<decimal> ThirdEvaluation { get; set; }
        public Nullable<decimal> FinalEvaluation { get; set; }
    }
}
