//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndorsementResult
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public long EndorsementId { get; set; }
        public bool ApprovedStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual Endorsement Endorsement { get; set; }
    }
}
