//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EServicesTabContent
    {
        public long Id { get; set; }
        public long TabId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ImagePath { get; set; }
        public string TitleAr { get; set; }
        public string TitleEn { get; set; }
        public string ShortDescriptionAr { get; set; }
        public string ShortDescriptionEn { get; set; }
        public string NavigationURL { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<bool> IsExternal { get; set; }
        public Nullable<bool> IsGeneral { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string ViewName { get; set; }
    }
}
