//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationGoalNote
    {
        public long Id { get; set; }
        public Nullable<long> OracelSerial { get; set; }
        public string NoteDescription { get; set; }
        public Nullable<int> SuggestedRelativeWeight { get; set; }
        public Nullable<int> SuggestedTargetOutput { get; set; }
        public long GoalId { get; set; }
        public long NoteMakerId { get; set; }
        public long NoteMakerName { get; set; }
        public string DirectorType { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual EvaluationGoal EvaluationGoal { get; set; }
    }
}
