//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationGadarhDegree
    {
        public long Id { get; set; }
        public Nullable<long> OracelSerial { get; set; }
        public long GadarhId { get; set; }
        public Nullable<decimal> FirstEvaluationDegree { get; set; }
        public Nullable<bool> IsFirstRejected { get; set; }
        public string FirstRejectReason { get; set; }
        public Nullable<decimal> SeconEvaluationDegree { get; set; }
        public Nullable<bool> IsSecondRejected { get; set; }
        public string SecondRejectReason { get; set; }
        public Nullable<decimal> FinalEvaluationDegree { get; set; }
        public Nullable<bool> IsHr { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedById { get; set; }
        public string CreatedByName { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedById { get; set; }
        public string ModifiedByName { get; set; }
    
        public virtual EvaluationGadarat EvaluationGadarat { get; set; }
    }
}
