//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluationPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EvaluationPlan()
        {
            this.EvaluationActions = new HashSet<EvaluationAction>();
            this.EvaluationGadarats = new HashSet<EvaluationGadarat>();
            this.EvaluationGoals = new HashSet<EvaluationGoal>();
        }
    
        public long Id { get; set; }
        public Nullable<long> OracelSerial { get; set; }
        public string PlanNumber { get; set; }
        public string PlanGuid { get; set; }
        public int StatusId { get; set; }
        public Nullable<bool> IsDraft { get; set; }
        public long EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeJob { get; set; }
        public string EmployeeSubDepCode { get; set; }
        public string EmployeeGeneralDepCode { get; set; }
        public long DirectorNumber { get; set; }
        public int EmployeeRank { get; set; }
        public long AuthorizedManager { get; set; }
        public Nullable<bool> GovernerIsFirstManager { get; set; }
        public Nullable<bool> HasSecondManager { get; set; }
        public string Department { get; set; }
        public string EmailId { get; set; }
        public string WorkPhoneNo { get; set; }
        public string Extention { get; set; }
        public string JobFamilyCode { get; set; }
        public string JobTitleCode { get; set; }
        public string GradeCode { get; set; }
        public string JobSerial { get; set; }
        public int CurrentVersion { get; set; }
        public Nullable<int> LastVersionInReview { get; set; }
        public Nullable<int> EmpolyeeOrgnizationalLevel { get; set; }
        public string ApproveChain { get; set; }
        public Nullable<long> CurrentApprovalId { get; set; }
        public string CurrentApprovalName { get; set; }
        public Nullable<long> NextApprovalId { get; set; }
        public string NextApprovalName { get; set; }
        public string CurrentUserAuthority { get; set; }
        public string NextUserAuthority { get; set; }
        public Nullable<int> PlanYear { get; set; }
        public Nullable<bool> PlanSentToHR { get; set; }
        public Nullable<System.DateTime> PlanAcceptanceDate { get; set; }
        public Nullable<bool> IsHrPlanTask { get; set; }
        public string EvaluationNumber { get; set; }
        public Nullable<decimal> FirstEvaluationDegree { get; set; }
        public Nullable<bool> IsEvaluationComplete { get; set; }
        public Nullable<bool> IsEvaluationEnded { get; set; }
        public Nullable<bool> IsEvalualtionFirstRejected { get; set; }
        public Nullable<bool> IsEvalualtionSecondRejected { get; set; }
        public Nullable<int> CurrentEvaluationVer { get; set; }
        public string ApplicantObjectionNote { get; set; }
        public Nullable<System.DateTime> ComitteeReviewDate { get; set; }
        public string ObjectionCommiteeNotes { get; set; }
        public string AuthManagerNotes { get; set; }
        public Nullable<byte> ObjectionNo { get; set; }
        public Nullable<bool> IsUpdateRequested { get; set; }
        public Nullable<decimal> FinalEvaluationDegree { get; set; }
        public Nullable<bool> EvaluationSentToHR { get; set; }
        public Nullable<decimal> EvaluationArithmeticMean { get; set; }
        public Nullable<bool> IsEmployeeMoved { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationAction> EvaluationActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationGadarat> EvaluationGadarats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluationGoal> EvaluationGoals { get; set; }
        public virtual EvaluationStatus EvaluationStatus { get; set; }
    }
}
