//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ASSESSMENT_COMPETENCY_DTL
    {
        public Nullable<double> CMP_NUM { get; set; }
        public Nullable<double> CATEGORY_CODE { get; set; }
        public Nullable<double> COMPETENCY_CODE { get; set; }
        public Nullable<double> SUB_COMPETENCY_CODE { get; set; }
        public string SUB_COMPETENCY_DES_NTV { get; set; }
        public string SUB_COMPETENCY_DES_FRN { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<short> ACTIVE_FLAG { get; set; }
        public string LAST_OPERATION { get; set; }
        public Nullable<System.DateTime> TIME_STAMP { get; set; }
    }
}
