//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ASSESMENT_COMPETENCIES
    {
        public short CMP_NUM { get; set; }
        public Nullable<double> APP_CODE { get; set; }
        public Nullable<double> APP_CHARTER { get; set; }
        public string DESCRIPTION_NTV { get; set; }
        public string DESCRIPTION_FRN { get; set; }
        public Nullable<double> COMPETENCY_TYPE { get; set; }
        public Nullable<int> COMPETENCY_LEVEL { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<short> ACTIVE_FLAG { get; set; }
        public string JOB_FAMILY_CODE { get; set; }
        public string JOB_TITLE_CODE { get; set; }
        public Nullable<double> COMPETENCY_CODE { get; set; }
        public Nullable<short> OBJECTION_FLAG { get; set; }
        public string OBJECTION_REASON { get; set; }
    }
}
