//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ASSESMENT_CHARTER
    {
        public short CMP_NUM { get; set; }
        public Nullable<double> APP_CODE { get; set; }
        public Nullable<double> APP_STATUS { get; set; }
        public double EMP_CODE { get; set; }
        public Nullable<double> DIRECTOR_CODE { get; set; }
        public string PLAN_NUMBER { get; set; }
        public Nullable<double> AUTHORIZED_MANAGER { get; set; }
        public Nullable<double> CURRENT_VERSION { get; set; }
        public Nullable<double> LAST_VERSION_IN_REVIEW { get; set; }
        public Nullable<double> FINAL_EVALUATION { get; set; }
        public Nullable<short> EVALUATION_COMPLETE_FLAG { get; set; }
        public string APPROVAL_CHAIN { get; set; }
        public Nullable<double> CURRENT_APPROVAL { get; set; }
        public Nullable<short> EVALUATION_END_FLAG { get; set; }
        public Nullable<double> CURRENT_EVALUAT_VERSION { get; set; }
        public string JOB_FAMILY_CODE { get; set; }
        public string JOB_TITLE_CODE { get; set; }
        public string GRADE_CODE { get; set; }
        public string JOB_SERIAL { get; set; }
        public string AUTH_MANAGER_NOTES { get; set; }
        public Nullable<double> AUTH_MANAGER_EVALUATION { get; set; }
        public string COMMITTEE_DECISIONS { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<short> ACTIVE_FLAG { get; set; }
        public Nullable<double> APP_DATE { get; set; }
        public Nullable<double> CHARTER_YEAR { get; set; }
        public Nullable<double> BILL_CURVE_APP_CODE { get; set; }
        public Nullable<double> ASSIGNED_TO { get; set; }
        public string UPDATE_REQUESTED { get; set; }
        public Nullable<double> STAGE_CODE { get; set; }
        public string DEPARTMENTID { get; set; }
        public Nullable<double> SENTTOHR { get; set; }
        public Nullable<double> EVALUATION_NO { get; set; }
        public Nullable<int> UPDATED_EVALUATION { get; set; }
    }
}
