//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCM_ASSESMENT_TASK
    {
        public short CMP_NUM { get; set; }
        public Nullable<double> APP_CODE { get; set; }
        public Nullable<double> APP_CHARTER { get; set; }
        public Nullable<double> APP_STATUS { get; set; }
        public Nullable<double> ASSIGNED_TO { get; set; }
        public Nullable<short> DIRECT_MANAGER_FLAG { get; set; }
        public Nullable<short> HUMAN_RESOURCE_FLAG { get; set; }
        public Nullable<short> DEPUTY_FLAG { get; set; }
        public Nullable<short> EVALUATION_FLAG { get; set; }
        public string FULL_NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> MOBILE { get; set; }
        public Nullable<short> APPROVE_REJ_STATUS_FLAG { get; set; }
        public string REJECT_REASON { get; set; }
        public Nullable<double> APPROVED_VERSION { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public string INSERT_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
        public Nullable<short> ACTIVE_FLAG { get; set; }
        public string MODIFY_USER_NAME { get; set; }
        public string ORIGINAL_EMP_CODE { get; set; }
    }
}
