//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MaintenanceRequest()
        {
            this.MaintenanceRequestActions = new HashSet<MaintenanceRequestAction>();
            this.RequestsAttachments = new HashSet<RequestsAttachment>();
            this.RequestSubstances = new HashSet<RequestSubstance>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public byte Language { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> ApplicantNo { get; set; }
        public string ApplicantName { get; set; }
        public long BeneficiaryNo { get; set; }
        public string BeneficiaryName { get; set; }
        public string EmailId { get; set; }
        public string WorkPhoneNo { get; set; }
        public string Extention { get; set; }
        public Nullable<long> SpecialistNo { get; set; }
        public string SpecialistName { get; set; }
        public string SupervisorName { get; set; }
        public Nullable<long> SupervisorNo { get; set; }
        public Nullable<long> HODNo { get; set; }
        public string HODName { get; set; }
        public Nullable<bool> IsEvaluated { get; set; }
        public Nullable<byte> EvaluationRate { get; set; }
        public string EvaluationNotes { get; set; }
        public Nullable<bool> IsOnBehave { get; set; }
        public string BuildingName { get; set; }
        public Nullable<long> BuildingCode { get; set; }
        public Nullable<long> FloorNumber { get; set; }
        public string FloorName { get; set; }
        public Nullable<int> SuiteNumber { get; set; }
        public string SuitName { get; set; }
        public string DisrepairDescription { get; set; }
        public string ApplicantNotes { get; set; }
        public string ServiceTypeName { get; set; }
        public Nullable<int> DurationPerDay { get; set; }
        public Nullable<int> ActualWorkDays { get; set; }
        public string UMInstructionForRequest { get; set; }
        public string UnderProccessingBy { get; set; }
        public Nullable<bool> IsUnderProccessing { get; set; }
        public Nullable<System.DateTime> UnderProccessingFrom { get; set; }
        public Nullable<bool> HasAttachmments { get; set; }
        public Nullable<bool> HasSubstances { get; set; }
        public Nullable<byte> NextAction { get; set; }
        public string WorkReport { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> SubstancesRejectedStatus { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaintenanceRequestAction> MaintenanceRequestActions { get; set; }
        public virtual MaintenanceStatus MaintenanceStatus { get; set; }
        public virtual MaintenanceService MaintenanceService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsAttachment> RequestsAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestSubstance> RequestSubstances { get; set; }
    }
}
