//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membership()
        {
            this.MembershipDiscounts = new HashSet<MembershipDiscount>();
            this.MembershipFeatures = new HashSet<MembershipFeature>();
        }
    
        public int Id { get; set; }
        public string MembershipGUID { get; set; }
        public int CustomerId { get; set; }
        public int PlanId { get; set; }
        public string PlanOrgNameAR { get; set; }
        public string PlanOrgNameEN { get; set; }
        public decimal PlanOrgPrice { get; set; }
        public int PlanOrgSequence { get; set; }
        public int PlanOrgDurationInMonths { get; set; }
        public int MembershipStatusId { get; set; }
        public string SadadNumber { get; set; }
        public decimal Amount { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaidDateTime { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> UpgradedDate { get; set; }
        public Nullable<bool> IsUpgraded { get; set; }
        public Nullable<bool> IsRenew { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsMigrated { get; set; }
        public Nullable<System.DateTime> MigratedOn { get; set; }
        public string MigratedBy { get; set; }
        public Nullable<bool> Published { get; set; }
    
        public virtual CustomerInformation CustomerInformation { get; set; }
        public virtual PlansGeneralInformation PlansGeneralInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipDiscount> MembershipDiscounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembershipFeature> MembershipFeatures { get; set; }
    }
}
