//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NRRCDb2Entities : DbContext
    {
        public NRRCDb2Entities()
            : base("name=NRRCDb2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<BasCity> BasCities { get; set; }
        public virtual DbSet<BasCountry> BasCountries { get; set; }
        public virtual DbSet<EntityProfile> EntityProfiles { get; set; }
        public virtual DbSet<FacilityProfile> FacilityProfiles { get; set; }
        public virtual DbSet<ItemSourcesFile> ItemSourcesFiles { get; set; }
        public virtual DbSet<ItemSourcesProfile> ItemSourcesProfiles { get; set; }
        public virtual DbSet<LegalRepresentativesProfile> LegalRepresentativesProfiles { get; set; }
        public virtual DbSet<LicenseInventoryLimit> LicenseInventoryLimits { get; set; }
        public virtual DbSet<LicenseProfile> LicenseProfiles { get; set; }
        public virtual DbSet<LookupSet> LookupSets { get; set; }
        public virtual DbSet<LookupSetTerm> LookupSetTerms { get; set; }
        public virtual DbSet<ManufacturerMaster> ManufacturerMasters { get; set; }
        public virtual DbSet<NuclearRelatedItemsProfile> NuclearRelatedItemsProfiles { get; set; }
        public virtual DbSet<PermitDetailsProfile> PermitDetailsProfiles { get; set; }
        public virtual DbSet<PermitInventoryLimit> PermitInventoryLimits { get; set; }
        public virtual DbSet<PractiseProfile> PractiseProfiles { get; set; }
        public virtual DbSet<RadiationGeneratorsProfile> RadiationGeneratorsProfiles { get; set; }
        public virtual DbSet<SafetyResponsibleOfficersProfile> SafetyResponsibleOfficersProfiles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
