//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NuclearRelatedItemsProfile
    {
        public int NRRCRelatedItemId { get; set; }
        public string RelatedItemDescAr { get; set; }
        public string RelatedItemDescEn { get; set; }
        public string NrrcID { get; set; }
        public string Status { get; set; }
        public string ManufacturerSerialNo { get; set; }
        public System.DateTime DateofManufacturing { get; set; }
        public string FacilityRelatedItemID { get; set; }
        public string Purpose { get; set; }
        public string ItemTypeNo { get; set; }
        public string ItemtypeName { get; set; }
        public string ModelNumber { get; set; }
        public string HSCode { get; set; }
        public string GovernmentCommitmentsFlag { get; set; }
        public string EndUserCertificateFlag { get; set; }
        public string Unit { get; set; }
        public int PermitInitialQty { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> LicenseInventoryId { get; set; }
        public Nullable<int> PermitdetailsId { get; set; }
        public Nullable<int> PermitInventoryId { get; set; }
        public Nullable<int> PractiseId { get; set; }
        public Nullable<int> SROId { get; set; }
        public Nullable<int> LegalRepresentativesId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> ManufactureCountryId { get; set; }
        public Nullable<int> ItemCategory { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual BasCountry BasCountry { get; set; }
        public virtual EntityProfile EntityProfile { get; set; }
        public virtual FacilityProfile FacilityProfile { get; set; }
        public virtual LegalRepresentativesProfile LegalRepresentativesProfile { get; set; }
        public virtual LicenseInventoryLimit LicenseInventoryLimit { get; set; }
        public virtual LicenseProfile LicenseProfile { get; set; }
        public virtual LookupSet LookupSet { get; set; }
        public virtual ManufacturerMaster ManufacturerMaster { get; set; }
        public virtual PermitDetailsProfile PermitDetailsProfile { get; set; }
        public virtual PermitInventoryLimit PermitInventoryLimit { get; set; }
        public virtual PractiseProfile PractiseProfile { get; set; }
        public virtual SafetyResponsibleOfficersProfile SafetyResponsibleOfficersProfile { get; set; }
    }
}
