//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitDetailsProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermitDetailsProfile()
        {
            this.ItemSourcesProfiles = new HashSet<ItemSourcesProfile>();
            this.NuclearRelatedItemsProfiles = new HashSet<NuclearRelatedItemsProfile>();
            this.PermitInventoryLimits = new HashSet<PermitInventoryLimit>();
            this.PractiseProfiles = new HashSet<PractiseProfile>();
            this.RadiationGeneratorsProfiles = new HashSet<RadiationGeneratorsProfile>();
        }
    
        public int PermitDetailsId { get; set; }
        public string PermitDetailsDescAr { get; set; }
        public string PermitDetailsDescEn { get; set; }
        public string PermitNumber { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<System.DateTime> AmanInsertedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSourcesProfile> ItemSourcesProfiles { get; set; }
        public virtual LicenseProfile LicenseProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuclearRelatedItemsProfile> NuclearRelatedItemsProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermitInventoryLimit> PermitInventoryLimits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PractiseProfile> PractiseProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadiationGeneratorsProfile> RadiationGeneratorsProfiles { get; set; }
    }
}
