//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileOfUser
    {
        public long Id { get; set; }
        public long EmployeeNo { get; set; }
        public string Username { get; set; }
        public string EmployeeName { get; set; }
        public string EmailId { get; set; }
        public string Department { get; set; }
        public string JobTitle { get; set; }
        public string WorkPhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Office { get; set; }
        public string Language { get; set; }
        public string ImagePath { get; set; }
        public string FirstManagerName { get; set; }
        public string SecondManagerName { get; set; }
        public string ThirdManagerName { get; set; }
        public string FourthManagerName { get; set; }
        public Nullable<long> FirstManagerId { get; set; }
        public Nullable<long> SecondManagerId { get; set; }
        public Nullable<long> ThirdManagerId { get; set; }
        public Nullable<long> FourthManagerId { get; set; }
        public string FirstManagerImagePath { get; set; }
        public string SecondManagerImagePath { get; set; }
        public string ThirdManagerImagePath { get; set; }
        public string FourthManagerImagePath { get; set; }
        public string GeneralDepartmentCode { get; set; }
        public string DepartmentCode { get; set; }
        public string GeneralDepartment { get; set; }
        public Nullable<System.DateTime> SyncDateTime { get; set; }
        public Nullable<bool> IsReporter { get; set; }
    }
}
