//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadiationGeneratorsProfile
    {
        public int EquipmentId { get; set; }
        public string EquipmentDescAr { get; set; }
        public string EquipmentDescEn { get; set; }
        public string NrrcID { get; set; }
        public string Status { get; set; }
        public string ManufacturerSerialNo { get; set; }
        public System.DateTime DateofManufacturing { get; set; }
        public string FacilitySerialNo { get; set; }
        public string Purpose { get; set; }
        public string ModelNumber { get; set; }
        public string XRayTubeSerialNo { get; set; }
        public string MaxEnergy { get; set; }
        public string EnergyUnit { get; set; }
        public string MaxDoseRate { get; set; }
        public string DoseUnit { get; set; }
        public string MaxCurrent { get; set; }
        public string Unit { get; set; }
        public string SheildMaterial { get; set; }
        public string ShieldNuclearMaterialCode { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> FacilityId { get; set; }
        public Nullable<int> LicenseId { get; set; }
        public Nullable<int> LicenseInventoryId { get; set; }
        public Nullable<int> PermitdetailsId { get; set; }
        public Nullable<int> PermitInventoryId { get; set; }
        public Nullable<int> PractiseId { get; set; }
        public Nullable<int> SROId { get; set; }
        public Nullable<int> LegalRepresentativesId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> EquipmentType { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual EntityProfile EntityProfile { get; set; }
        public virtual FacilityProfile FacilityProfile { get; set; }
        public virtual LegalRepresentativesProfile LegalRepresentativesProfile { get; set; }
        public virtual LicenseInventoryLimit LicenseInventoryLimit { get; set; }
        public virtual LicenseProfile LicenseProfile { get; set; }
        public virtual LookupSet LookupSet { get; set; }
        public virtual ManufacturerMaster ManufacturerMaster { get; set; }
        public virtual PermitDetailsProfile PermitDetailsProfile { get; set; }
        public virtual PermitInventoryLimit PermitInventoryLimit { get; set; }
        public virtual PractiseProfile PractiseProfile { get; set; }
        public virtual SafetyResponsibleOfficersProfile SafetyResponsibleOfficersProfile { get; set; }
    }
}
