//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservationRequestAction
    {
        public int Id { get; set; }
        public int RoomReservationId { get; set; }
        public int ActionType { get; set; }
        public long ActionById { get; set; }
        public string ActionText { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual RoomReservationRequest RoomReservationRequest { get; set; }
    }
}
