//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAuthorized
    {
        public int Id { get; set; }
        public long EmployeeNo { get; set; }
        public bool IsPublicRelationsDirector { get; set; }
        public bool IsMediaAwarenessDepartmentDirector { get; set; }
        public bool IsMarketingDirector { get; set; }
        public bool IsDirectorServicesHospitalityDirector { get; set; }
        public bool IsITDirector { get; set; }
        public bool IsFacilitiesDirectors { get; set; }
        public bool IsMediaAwarenessDepartmentSpecialist { get; set; }
        public bool IsMarketingSpecialist { get; set; }
        public bool IsDirectorServicesHospitalitySpecialist { get; set; }
        public bool IsPublicRelationsSpecialist { get; set; }
        public Nullable<bool> IsDelegated { get; set; }
        public Nullable<long> DelegatedToEmployeeNo { get; set; }
        public Nullable<System.DateTime> DelegationStartDate { get; set; }
        public Nullable<System.DateTime> DelegationEndDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
