//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafetyResponsibleOfficersProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SafetyResponsibleOfficersProfile()
        {
            this.ItemSourcesProfiles = new HashSet<ItemSourcesProfile>();
            this.NuclearRelatedItemsProfiles = new HashSet<NuclearRelatedItemsProfile>();
            this.RadiationGeneratorsProfiles = new HashSet<RadiationGeneratorsProfile>();
        }
    
        public int SROId { get; set; }
        public string SRONameAr { get; set; }
        public string SRONameEn { get; set; }
        public string NationalID { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string CertificateNo { get; set; }
        public System.DateTime IssuanceDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> AmanInsertedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSourcesProfile> ItemSourcesProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NuclearRelatedItemsProfile> NuclearRelatedItemsProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadiationGeneratorsProfile> RadiationGeneratorsProfiles { get; set; }
    }
}
