//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimCardRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimCardRequest()
        {
            this.SimCardRequestActions = new HashSet<SimCardRequestAction>();
            this.SimCardRequestSpecialists = new HashSet<SimCardRequestSpecialist>();
            this.SimRequestServices = new HashSet<SimRequestService>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public byte Language { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public Nullable<long> ApplicantNo { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantType { get; set; }
        public string Department { get; set; }
        public string EmailId { get; set; }
        public string WorkNature { get; set; }
        public string RequestReasons { get; set; }
        public string WorkPhoneNo { get; set; }
        public string Extention { get; set; }
        public Nullable<long> SpecialistNo { get; set; }
        public string SpecialistName { get; set; }
        public Nullable<long> CurrentApprovalId { get; set; }
        public string CurrentApprovalName { get; set; }
        public Nullable<long> NextApprovalId { get; set; }
        public string NextApprovalName { get; set; }
        public string CurrentUserAuthority { get; set; }
        public string NextUserAuthority { get; set; }
        public string ApplicantNotes { get; set; }
        public Nullable<int> UseDuration { get; set; }
        public Nullable<int> ExtendUseDuration { get; set; }
        public string SpecialistNotes { get; set; }
        public Nullable<bool> IsConfirmedBySpecialist { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UseFromDate { get; set; }
        public string UseTillDate { get; set; }
        public string ExtendUseTillDate { get; set; }
        public string HelpType { get; set; }
        public string UpdateType { get; set; }
        public string OtherTypeText { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual SASOArea SASOArea { get; set; }
        public virtual ServicesStatus ServicesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCardRequestAction> SimCardRequestActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimCardRequestSpecialist> SimCardRequestSpecialists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SimRequestService> SimRequestServices { get; set; }
    }
}
