//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimRequestService
    {
        public long Id { get; set; }
        public int ServiceId { get; set; }
        public Nullable<long> RequestId { get; set; }
        public Nullable<long> DeviceId { get; set; }
        public Nullable<long> UtilityTypeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual AvailableDevice AvailableDevice { get; set; }
        public virtual DataSimService DataSimService { get; set; }
        public virtual SimCardRequest SimCardRequest { get; set; }
    }
}
