//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyRelatedUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SurveyRelatedUser()
        {
            this.SurveyActionPolls = new HashSet<SurveyActionPoll>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SurveyId { get; set; }
        public Nullable<long> UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserJobTitle { get; set; }
        public Nullable<long> UserDepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SurveyActionPoll> SurveyActionPolls { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
