//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranslationRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TranslationRequest()
        {
            this.TranslationRequestActions = new HashSet<TranslationRequestAction>();
            this.TrRequestsAttachments = new HashSet<TrRequestsAttachment>();
            this.TRRequestServices = new HashSet<TRRequestService>();
            this.TrRequestSpecialists = new HashSet<TrRequestSpecialist>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public byte Language { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public string TranslationType { get; set; }
        public Nullable<long> ApplicantNo { get; set; }
        public string ApplicantName { get; set; }
        public string Department { get; set; }
        public string EmailId { get; set; }
        public string WorkPhoneNo { get; set; }
        public string Extention { get; set; }
        public Nullable<long> SpecialistNo { get; set; }
        public string SpecialistName { get; set; }
        public Nullable<long> HODNo { get; set; }
        public string HODName { get; set; }
        public string ApplicantNotes { get; set; }
        public string ServiceTypeName { get; set; }
        public Nullable<int> DurationPerDay { get; set; }
        public Nullable<int> ActualWorkDays { get; set; }
        public Nullable<bool> HasAttachmments { get; set; }
        public Nullable<bool> HasMultipleSpecialists { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranslationRequestAction> TranslationRequestActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrRequestsAttachment> TrRequestsAttachments { get; set; }
        public virtual TranslationStatus TranslationStatus { get; set; }
        public virtual TranslationServiceCategory TranslationServiceCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRRequestService> TRRequestServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrRequestSpecialist> TrRequestSpecialists { get; set; }
    }
}
