//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class updEmployeeApproval
    {
        public int Id { get; set; }
        public int EmployeeNo { get; set; }
        public bool BasicApproval { get; set; }
        public bool FamilyApproval { get; set; }
        public bool PhotoApproval { get; set; }
        public bool QualificationApproval { get; set; }
        public bool TrainingApproval { get; set; }
        public bool ExpiranceApproval { get; set; }
        public bool IsActive { get; set; }
    }
}
