//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class updEmployeeFamilyMembersDetail
    {
        public long Id { get; set; }
        public long MasterId { get; set; }
        public int EmployeeId { get; set; }
        public string NameAr { get; set; }
        public string NameEn { get; set; }
        public string Relation { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string IdNo { get; set; }
        public byte[] Card { get; set; }
        public string CardName { get; set; }
        public string CardContentType { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual updEmployeeFamilyMember updEmployeeFamilyMember { get; set; }
    }
}
