//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class updEmployeePhoto
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoName { get; set; }
        public string PhotoContentType { get; set; }
        public int StatusId { get; set; }
        public string StatusText { get; set; }
        public int NextApproval { get; set; }
        public bool SentToHr { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
