//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class updEmployeeBasic
    {
        public long Id { get; set; }
        public int EmployeeId { get; set; }
        public string IdentityId { get; set; }
        public string IssuanceOfIdentityCity { get; set; }
        public Nullable<System.DateTime> IssuanceOfIdentityDate { get; set; }
        public Nullable<System.DateTime> ExpireationOfIdentityDate { get; set; }
        public byte[] IdentityAttachment { get; set; }
        public string IdentityAttachmentContentType { get; set; }
        public string IdentityAttachmentName { get; set; }
        public string FirstName { get; set; }
        public string FirstNameEn { get; set; }
        public string SecondName { get; set; }
        public string SecondNameEn { get; set; }
        public string ThirdName { get; set; }
        public string ThirdNameEn { get; set; }
        public string FamilyName { get; set; }
        public string FamilyNameEn { get; set; }
        public string Sex { get; set; }
        public string BloodType { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string ExtensionNo { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string ContactName { get; set; }
        public string ContactMobile { get; set; }
        public string ContactRelation { get; set; }
        public string BuildingNo { get; set; }
        public string CityDescription { get; set; }
        public string AreaDescription { get; set; }
        public string ZipCode { get; set; }
        public string StreetName { get; set; }
        public string UnitNo { get; set; }
        public string AdditionalNo { get; set; }
        public int StatusId { get; set; }
        public string StatusText { get; set; }
        public int NextApproval { get; set; }
        public bool SentToHr { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
