//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersData
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string EduEntity { get; set; }
        public string EduPlace { get; set; }
        public string EduFaculty { get; set; }
        public string EduUniversityNum { get; set; }
        public string AccumType { get; set; }
        public string AccuNumber { get; set; }
        public string User_SPID { get; set; }
        public string User_SPLoginName { get; set; }
        public string Track { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
