//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInDepartments1
    {
        public long Id { get; set; }
        public int DepartmentId { get; set; }
        public long EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string BranchName { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> ServiceTypeId { get; set; }
        public string ServiceName { get; set; }
        public string EmailId { get; set; }
        public string JobTitle { get; set; }
        public string WorkPhoneNo { get; set; }
        public Nullable<long> ManagerEmployeeNo { get; set; }
        public string ManagerName { get; set; }
        public Nullable<long> DelegatedFrom { get; set; }
        public Nullable<bool> IsDelegated { get; set; }
        public Nullable<long> DelegatedTo { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}
