//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VisaRequest()
        {
            this.VisaRequestActions = new HashSet<VisaRequestAction>();
            this.VisaRequestAttachments = new HashSet<VisaRequestAttachment>();
            this.VisaRequestCmopanions = new HashSet<VisaRequestCmopanion>();
        }
    
        public long Id { get; set; }
        public string RequestNo { get; set; }
        public byte Language { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<long> BranchId { get; set; }
        public Nullable<long> AreaId { get; set; }
        public Nullable<long> ApplicantNo { get; set; }
        public string ApplicantName { get; set; }
        public string ApplicantType { get; set; }
        public string Department { get; set; }
        public string EmailId { get; set; }
        public string WorkPhoneNo { get; set; }
        public string Extention { get; set; }
        public Nullable<bool> HasMultiCompanion { get; set; }
        public string RequestReasons { get; set; }
        public Nullable<long> CurrentApprovalId { get; set; }
        public string CurrentApprovalName { get; set; }
        public Nullable<long> NextApprovalId { get; set; }
        public string NextApprovalName { get; set; }
        public string CurrentUserAuthority { get; set; }
        public string NextUserAuthority { get; set; }
        public Nullable<bool> IsGMUpdateRequest { get; set; }
        public Nullable<bool> IsGMFinanceUpdateRequest { get; set; }
        public Nullable<bool> IsFaciltiesDirectorUpdateRequest { get; set; }
        public string MOFARequestNumber { get; set; }
        public string MOFAVisaNumber { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ServicesStatus ServicesStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisaRequestAction> VisaRequestActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisaRequestAttachment> VisaRequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisaRequestCmopanion> VisaRequestCmopanions { get; set; }
    }
}
