//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisaRequestAction
    {
        public long Id { get; set; }
        public long RequestId { get; set; }
        public Nullable<long> ActionMaker { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string Notes { get; set; }
        public string RejectReason { get; set; }
        public string ActionMakerName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ServicesStatus ServicesStatus { get; set; }
        public virtual VisaRequest VisaRequest { get; set; }
    }
}
