//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class vm_availabledevices
    {
        public long Id { get; set; }
        public Nullable<long> UtilitiyTypeId { get; set; }
        public string ArName { get; set; }
        public string EnName { get; set; }
        public string TypeName { get; set; }
        public string ArDisplayName { get; set; }
        public string EnDisplayName { get; set; }
        public string DeviceSimCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
        public long DeviceAvailability { get; set; }
        public string RequestNo { get; set; }
        public string ApplicantName { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> RequestModified { get; set; }
    }
}
